config/routes.rb
Rails.application.routes.draw do
  # get 'cards_controller/index'
  # get 'welcome/index'
  resources :cards


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  validates :original_text, :translated_text, presence: true
  #validates :original_text, uniqueness: true
  validates_with CardValidator
  before_validation :change_review_date

  #private
  def change_review_date
  	self.review_date = 3.days.from_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  def index
    @cards = Card.all
  end

  def new
  	@card = Card.new
  end

  def create
  	@card = Card.new(card_params)

    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  def update
    @card = Card.find(params[:id])
 
    if @card.update(card_params)
      redirect_to @card
    else
      render 'edit'
    end
  end


  def show
    @card = Card.find(params[:id])
  end

  def edit
    @card = Card.find(params[:id])
  end

  def destroy
    @card = Card.find(params[:id])
    @card.destroy

    redirect_to cards_path  
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @cards = Card.all
    @card = Card.(params[1])
end

  def new
    @card = Card.new
  end  

  def show
     @card = Card.find(params[:id])
  end
  
  def create
  	@card = Card.new(params[:card])

    if @card.save
      redirect_to @card
    else
      render 'new'
    end
  end

  private
    def card_params
      params.require(:card).permit(:original_text, :translated_text, :review_date)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cards/edit.html.erb
<section>
  <p style="font-size: 22px;">
    РЕДАКТИРУЕТСЯ КАРТОЧКА:
  </p>

  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2>
        <% pluralize(@card.errors.count, "error") %> 
        эта карточка запонена некорректно! ошибки:
      </h2>
      <ul>
        <% @card.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for :card, url: card_path(@card), method: :patch do |f| %>
    <p>
      <%= f.label :original_text %><br>
      <%= f.text_field :original_text %>
    </p>
   
    <p>
      <%= f.label :translated_text %><br>
      <%= f.text_field :translated_text %>
    </p>
   
    <p>
      <%= f.submit 'Обновить'%>
    </p>
  <% end %>

  <%= link_to 'Назад', root_path %>   

</section>

app/views/cards/index.html.erb
<section>
  <p style="font-size: 22px;">
    ВСЕ КАРТОЧКИ:
  </p>
  <% @cards.each do |card|%>
    <tr>
      <td><%=card.review_date %></td> 
      <td><%=card.original_text %></td> 
      <td><%=card.translated_text %></td>  
      <td><%= link_to 'Изменить  ', edit_card_path(card) %> </td>     
      <td><%= link_to 'Удалить  ', card_path(card),
        method: :delete %> </td><br> 
    </tr>
  <% end %>
  <br>
  <%= link_to 'Назад', root_path %>   

</section>

app/views/cards/new.html.erb
<section>
  <p style="font-size: 22px;">
    НОВАЯ КАРТОЧКА:
  </p>

  <%= form_for :card, url: cards_path do |f| %>
    <p>
      <%= f.label :original_text %><br>
      <%= f.text_field :original_text %>
    </p>
   
    <p>
      <%= f.label :translated_text %><br>
      <%= f.text_field :translated_text %>
    </p>
   
    <p>
      <%= f.submit 'Сохранить'%>
    </p>
  <% end %>

  <%= link_to 'Назад', root_path %>   

</section>

app/views/cards/show.html.erb
<section>
  <p style="font-size: 22px;">
    КАРТОЧКА ЗАПИСАНА В БАЗУ ДАННЫХ!
  </p>  <br>
<%= link_to 'Изменить карточку', edit_card_path(@card) %> 
<br>
  <%= link_to 'Готово!', cards_path %>   
</section>

app/views/cards_controller/index.html.erb
<body>
  <section id="container">

    <header class="clearfix">
      <h1>Флэшкарточкер</h1>
<!--       <ul class="navigation-links">
        <li><a href="#">Все карточки</a></li>
        <li><a href="#">Добавить карточку</a></li>
      </ul>
 -->    </header>

    <section>
      <p style="font-size: 22px;">
        ВСЕ КАРТОЧКИ:
      </p>
      <% @cards.each do |card|%>
        <tr>
          <td><%=card.review_date %></td> ==
          <td><%=card.original_text %></td> ==
          <td><%=card.translated_text %></td> <br> 
        </tr>
      <% end %>
    </section>

  </section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Flashcards</title>
  <link rel="stylesheet" href="application.css">
  <%= stylesheet_link_tag    'application' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

  <body>
   <%=yield%>
  </body>

app/views/welcome/index.html.erb
    <header class="clearfix">
      <h1>Флэшкарточкер</h1>
<!--       <ul class="navigation-links">
        <li><a href="#">Все карточки</a></li>
        <li><a href="#">Добавить карточку</a></li>
      </ul>
 -->    </header>

  <p style="font-size: 22px;">
    Случайная карточка:
  </p>  <br>
  
  <%= form_for :card, url: card_path(@card), method: :patch do |f| %>
    <p>
      <%= f.label :original_text %><br>
      <%= f.text_field :original_text %>
    </p>
   
    <p>
      <%= f.label :translated_text %><br>
      <%= f.text_field :translated_text %>
    </p>
   
    <p>
      <%= f.submit 'Обновить'%>
    </p>
  <% end %>

    <section>
      <%= link_to 'Все карточки', cards_path %> <br>
      <%= link_to 'Добавить карточку', new_card_path %>
    </section>

<!--       <p style="font-size: 22px;">
        Первый в мире удобный менеджер флеш-карточек. Именно так.
      </p>
 -->